Stop expand if no more places for expanding
It complained "AttributeError: 'NoneType' object has no attribute 'rounded'" when my bot take every available places to build  main bases.  In that case, the location got from `get_next_expansion` will be None and cause the error.